apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: ui
    tier: frontend
spec:
  # here we select the number of pods we wish to start and the selector that tells our replica set which pods it needs 
  #  to manage
  replicas: 2
  selector:  
    matchLabels:
      tier: frontend
  template:  
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: bearapp
        image: supergiantkir/animals:bear
        volumeMounts:
        - mountPath: /test-pd
          name: test-volume
  volumes:
  - name: test-volume
    hostPath:
    # directory location on host
    path: /data
    # this field is optional
    type: Directory
